### PR TITLE
Update version number

### PR DESCRIPTION
**Pull request by rdeveen**
Of course, this number has to be updated to. @Bas-kolthof-triple

### CODE REVIEW

**Comment by rdeveen** [comment]
#3

**Comment by rdeveen** [comment]
See also https://github.com/wearetriple/ados-extension-ssl-custom-domain/runs/4693045331?check_suite_focus=true

**Comment by rdeveen** [comment]
@Bas-kolthof-triple something to approve before the weekend?

**Comment by Bas-kolthof-triple** [comment]
whoops. yes. lets.

**Pull request merged**
